import React from 'react'
import { Container, ChappterWrapper } from './styles'

import { ButtonChapter } from '../../../../components/ButtonChapter'
import { Header } from '../../../../components/Header'
import { ScrollView } from 'react-native'

export function Salmos() {
  return (
    <Container>
      <Header onPress={() => {}} title="Salmos" />
      <ScrollView showsVerticalScrollIndicator={false}>
        <ChappterWrapper>
          <ButtonChapter onPress={() => {}} title="1" />
          <ButtonChapter onPress={() => {}} title="2" />
          <ButtonChapter onPress={() => {}} title="3" />
          <ButtonChapter onPress={() => {}} title="4" />
          <ButtonChapter onPress={() => {}} title="5" />
          <ButtonChapter onPress={() => {}} title="6" />
          <ButtonChapter onPress={() => {}} title="7" />
          <ButtonChapter onPress={() => {}} title="8" />
          <ButtonChapter onPress={() => {}} title="9" />
          <ButtonChapter onPress={() => {}} title="10" />
          <ButtonChapter onPress={() => {}} title="11" />
          <ButtonChapter onPress={() => {}} title="12" />
          <ButtonChapter onPress={() => {}} title="13" />
          <ButtonChapter onPress={() => {}} title="14" />
          <ButtonChapter onPress={() => {}} title="15" />
          <ButtonChapter onPress={() => {}} title="16" />
          <ButtonChapter onPress={() => {}} title="17" />
          <ButtonChapter onPress={() => {}} title="18" />
          <ButtonChapter onPress={() => {}} title="19" />
          <ButtonChapter onPress={() => {}} title="20" />
          <ButtonChapter onPress={() => {}} title="21" />
          <ButtonChapter onPress={() => {}} title="22" />
          <ButtonChapter onPress={() => {}} title="23" />
          <ButtonChapter onPress={() => {}} title="24" />
          <ButtonChapter onPress={() => {}} title="25" />
          <ButtonChapter onPress={() => {}} title="26" />
          <ButtonChapter onPress={() => {}} title="27" />
          <ButtonChapter onPress={() => {}} title="28" />
          <ButtonChapter onPress={() => {}} title="29" />
          <ButtonChapter onPress={() => {}} title="30" />
          <ButtonChapter onPress={() => {}} title="31" />
          <ButtonChapter onPress={() => {}} title="32" />
          <ButtonChapter onPress={() => {}} title="33" />
          <ButtonChapter onPress={() => {}} title="34" />
          <ButtonChapter onPress={() => {}} title="35" />
          <ButtonChapter onPress={() => {}} title="36" />
          <ButtonChapter onPress={() => {}} title="37" />
          <ButtonChapter onPress={() => {}} title="38" />
          <ButtonChapter onPress={() => {}} title="39" />
          <ButtonChapter onPress={() => {}} title="40" />
          <ButtonChapter onPress={() => {}} title="41" />
          <ButtonChapter onPress={() => {}} title="42" />
          <ButtonChapter onPress={() => {}} title="43" />
          <ButtonChapter onPress={() => {}} title="44" />
          <ButtonChapter onPress={() => {}} title="45" />
          <ButtonChapter onPress={() => {}} title="46" />
          <ButtonChapter onPress={() => {}} title="47" />
          <ButtonChapter onPress={() => {}} title="48" />
          <ButtonChapter onPress={() => {}} title="49" />
          <ButtonChapter onPress={() => {}} title="50" />
          <ButtonChapter onPress={() => {}} title="51" />
          <ButtonChapter onPress={() => {}} title="52" />
          <ButtonChapter onPress={() => {}} title="53" />
          <ButtonChapter onPress={() => {}} title="54" />
          <ButtonChapter onPress={() => {}} title="55" />
          <ButtonChapter onPress={() => {}} title="56" />
          <ButtonChapter onPress={() => {}} title="57" />
          <ButtonChapter onPress={() => {}} title="58" />
          <ButtonChapter onPress={() => {}} title="59" />
          <ButtonChapter onPress={() => {}} title="60" />
          <ButtonChapter onPress={() => {}} title="61" />
          <ButtonChapter onPress={() => {}} title="62" />
          <ButtonChapter onPress={() => {}} title="63" />
          <ButtonChapter onPress={() => {}} title="64" />
          <ButtonChapter onPress={() => {}} title="65" />
          <ButtonChapter onPress={() => {}} title="66" />
          <ButtonChapter onPress={() => {}} title="67" />
          <ButtonChapter onPress={() => {}} title="68" />
          <ButtonChapter onPress={() => {}} title="69" />
          <ButtonChapter onPress={() => {}} title="70" />
          <ButtonChapter onPress={() => {}} title="71" />
          <ButtonChapter onPress={() => {}} title="72" />
          <ButtonChapter onPress={() => {}} title="73" />
          <ButtonChapter onPress={() => {}} title="74" />
          <ButtonChapter onPress={() => {}} title="75" />
          <ButtonChapter onPress={() => {}} title="76" />
          <ButtonChapter onPress={() => {}} title="77" />
          <ButtonChapter onPress={() => {}} title="78" />
          <ButtonChapter onPress={() => {}} title="79" />
          <ButtonChapter onPress={() => {}} title="80" />
          <ButtonChapter onPress={() => {}} title="81" />
          <ButtonChapter onPress={() => {}} title="82" />
          <ButtonChapter onPress={() => {}} title="83" />
          <ButtonChapter onPress={() => {}} title="84" />
          <ButtonChapter onPress={() => {}} title="85" />
          <ButtonChapter onPress={() => {}} title="86" />
          <ButtonChapter onPress={() => {}} title="87" />
          <ButtonChapter onPress={() => {}} title="88" />
          <ButtonChapter onPress={() => {}} title="89" />
          <ButtonChapter onPress={() => {}} title="90" />
          <ButtonChapter onPress={() => {}} title="91" />
          <ButtonChapter onPress={() => {}} title="92" />
          <ButtonChapter onPress={() => {}} title="93" />
          <ButtonChapter onPress={() => {}} title="94" />
          <ButtonChapter onPress={() => {}} title="95" />
          <ButtonChapter onPress={() => {}} title="96" />
          <ButtonChapter onPress={() => {}} title="97" />
          <ButtonChapter onPress={() => {}} title="98" />
          <ButtonChapter onPress={() => {}} title="99" />
          <ButtonChapter onPress={() => {}} title="100" />
          <ButtonChapter onPress={() => {}} title="101" />
          <ButtonChapter onPress={() => {}} title="102" />
          <ButtonChapter onPress={() => {}} title="103" />
          <ButtonChapter onPress={() => {}} title="104" />
          <ButtonChapter onPress={() => {}} title="105" />
          <ButtonChapter onPress={() => {}} title="106" />
          <ButtonChapter onPress={() => {}} title="107" />
          <ButtonChapter onPress={() => {}} title="108" />
          <ButtonChapter onPress={() => {}} title="109" />
          <ButtonChapter onPress={() => {}} title="110" />
          <ButtonChapter onPress={() => {}} title="111" />
          <ButtonChapter onPress={() => {}} title="112" />
          <ButtonChapter onPress={() => {}} title="113" />
          <ButtonChapter onPress={() => {}} title="114" />
          <ButtonChapter onPress={() => {}} title="115" />
          <ButtonChapter onPress={() => {}} title="116" />
          <ButtonChapter onPress={() => {}} title="117" />
          <ButtonChapter onPress={() => {}} title="118" />
          <ButtonChapter onPress={() => {}} title="119" />
          <ButtonChapter onPress={() => {}} title="120" />
          <ButtonChapter onPress={() => {}} title="121" />
          <ButtonChapter onPress={() => {}} title="122" />
          <ButtonChapter onPress={() => {}} title="123" />
          <ButtonChapter onPress={() => {}} title="124" />
          <ButtonChapter onPress={() => {}} title="125" />
          <ButtonChapter onPress={() => {}} title="126" />
          <ButtonChapter onPress={() => {}} title="127" />
          <ButtonChapter onPress={() => {}} title="128" />
          <ButtonChapter onPress={() => {}} title="129" />
          <ButtonChapter onPress={() => {}} title="130" />
          <ButtonChapter onPress={() => {}} title="131" />
          <ButtonChapter onPress={() => {}} title="132" />
          <ButtonChapter onPress={() => {}} title="133" />
          <ButtonChapter onPress={() => {}} title="134" />
          <ButtonChapter onPress={() => {}} title="135" />
          <ButtonChapter onPress={() => {}} title="136" />
          <ButtonChapter onPress={() => {}} title="137" />
          <ButtonChapter onPress={() => {}} title="138" />
          <ButtonChapter onPress={() => {}} title="139" />
          <ButtonChapter onPress={() => {}} title="140" />
          <ButtonChapter onPress={() => {}} title="141" />
          <ButtonChapter onPress={() => {}} title="142" />
          <ButtonChapter onPress={() => {}} title="143" />
          <ButtonChapter onPress={() => {}} title="144" />
          <ButtonChapter onPress={() => {}} title="145" />
          <ButtonChapter onPress={() => {}} title="146" />
          <ButtonChapter onPress={() => {}} title="147" />
          <ButtonChapter onPress={() => {}} title="148" />
          <ButtonChapter onPress={() => {}} title="149" />
          <ButtonChapter onPress={() => {}} title="150" />
        </ChappterWrapper>
      </ScrollView>
    </Container>
  )
}
